apiVersion: apps/v1
kind: Deployment
metadata:
  name: medas-financial-reporting
  namespace: user-paleo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medas-financial-reporting
  template:
    metadata:
      labels:
        app: medas-financial-reporting
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "student"
        vault.hashicorp.com/agent-inject-secret-s3-creds: "onyxia-kv/paleo/s3-credentials"
        vault.hashicorp.com/agent-inject-template-s3-creds: |
          {{- with secret "onyxia-kv/paleo/s3-credentials" -}}
          export AWS_ACCESS_KEY_ID="{{ .Data.data.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="{{ .Data.data.AWS_SECRET_ACCESS_KEY }}"
          {{- end -}}
    spec:
      containers:
        - name: medas-financial-reporting
          image: lpanier/visualisation-performances-sportives:latest
          command:
            - "sh"
            - "-c"
            - "source /vault/secrets/s3-creds && uv run streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
          ports:
            - containerPort: 8501
          env:
            - name: AWS_S3_ENDPOINT
              value: "https://minio.lab.sspcloud.fr"
            - name: S3_BUCKET
              value: "paleo"