apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-minio-credentials
  namespace: user-paleo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: minio-credentials
  data:
    - secretKey: access-key
      remoteRef:
        key: onyxia-kv/paleo/s3-credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: secret-key
      remoteRef:
        key: onyxia-kv/paleo/s3-credentials
        property: AWS_SECRET_ACCESS_KEY