apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medas-financial-reporting
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - sports-lx345.lab.sspcloud.fr
  rules:
    - host: sports-lx345.lab.sspcloud.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: medas-financial-reporting
                port:
                  number: 80